add_newline = false
format = """\
${custom.kaklsp_progress}\
${custom.kakcursor}\
${custom.kakposition}\
${custom.kakmode}\
${custom.kakcontext}\
$directory\
${custom.kakfile}\
${custom.kakfiletype}\
${custom.kaklsp_err}\
${custom.kaklsp_warn}\
${custom.kaklsp_hint}\
${custom.kaklsp_code_actions}\
$package\
$git_branch\
$git_commit\
$git_state\
$git_status\
${custom.kaksession}\
$memory_usage\
$battery\
$time\
${custom.kaktime}"""

[time]
format = "[ $time ]($style inverted)"
style = ""
time_format = "%H:%M"
disabled = false

[git_branch]
format = '[ $branch ]($style inverted)'
style = ''
truncation_length = 12
truncation_symbol = '…'
only_attached = false
always_show_remote = true
disabled = false

[git_commit]
style = ''
format = '[ $hash$tag ]($style inverted)'
commit_hash_length = 7
only_detached = false
tag_symbol = ' 笠'
tag_disabled = false
disabled = false

[git_state]
format = '\( [$state($progress_current/$progress_total)]($style inverted)\)'
style = ''
rebase = 'REBASING'
merge = 'MERGING'
revert = 'REVERTING'
cherry_pick = 'CHERRY-PICKING'
bisect = 'BISECTING'
am = 'AM'
am_or_rebase = 'AM/REBASE'
disabled = false

[git_status]
style = 'bold'
format = '[ \[$all_status$ahead_behind\] ]($style inverted)'
stashed = '\$'
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
conflicted = '='
deleted = '✘'
renamed = '»'
modified = '!'
staged = '+'
untracked = '?'
disabled = false

[directory]
format = '($style inverted)[$read_only]($read_only_style)[ $path]($style inverted)'
truncation_length = 3
truncate_to_repo = false
fish_style_pwd_dir_length = 0
use_logical_path = true
style = ''
read_only_style = 'fg:200'
read_only = '[]'
truncation_symbol = '…'
disabled = false

[directory.substitutions]
"~"         = ""
"~/.config" = ""

[package]
format = '[  $version]($style inverted)[ ]($style inverted)'
style = ''
display_private = true
disabled = false

[battery]
format = "[ $symbol$percentage]($style inverted) "
charging_symbol = ' '
discharging_symbol = ' '
disabled = false

[[battery.display]]
threshold = 10
style = ""
charging_symbol = ' '
discharging_symbol = ' '

[[battery.display]]
threshold = 20
style = ""
charging_symbol = ' '
discharging_symbol = ' '

[[battery.display]]
threshold = 30
style = ""
charging_symbol = ' '
discharging_symbol = ' '

[[battery.display]]
threshold = 40
style = ""
charging_symbol = ' '
discharging_symbol = ' '

[[battery.display]]
threshold = 50
style = ""
charging_symbol = ' '
discharging_symbol = ' '

[[battery.display]]
threshold = 60
style = ""
charging_symbol = ' '
discharging_symbol = ' '

[[battery.display]]
threshold = 70
style = ""
charging_symbol = ' '
discharging_symbol = ' '

[[battery.display]]
threshold = 80
style = ""
charging_symbol = ' '
discharging_symbol = ' '

[[battery.display]]
threshold = 90
style = ""
charging_symbol = ' '
discharging_symbol = ' '

[[battery.display]]
threshold = 100
style = ""
charging_symbol = ' '
discharging_symbol = ' '

[memory_usage]
format = "[  ${ram}]($style inverted)"
style = ""
threshold = -1
disabled = true

[custom.kakfile]
description = 'The current Kakoune buffername'
style = 'bold'
format = '[/$output  ]($style inverted)'
command = 'echo -n ${kak_buffile##*/}'
when = 'true'
shell = ['sh']
disabled = false

[custom.kaksession]
description = 'The current Kakoune session'
style = 'italic'
format = '[]($style inverted)[  %val{client}:%val{session} ]($style inverted)[]'
when = ''
shell = ['true']
disabled = true

[custom.kakcursor]
description = 'The current Kakoune cursor position'
style = ''
format = '[ %val{cursor_line}:%val{cursor_char_column} ]($style inverted)'
when = ''
shell = ['true']
disabled = false

[custom.kakmode]
description = 'The current Kakoune mode'
format = ' {{mode_info}}'
when = ''
shell = ['true']
disabled = false

[custom.kakcontext]
description = 'The current Kakoune context'
format = ' {{context_info}}'
when = ''
shell = ['true']
disabled = false

[custom.kakfiletype]
description = 'The current buffer filetype'
format = '\[%opt{filetype}\]'
when = ''
shell = ['true']
disabled = true

[custom.kakposition]
description = 'Relative position of the cursor inside the buffer'
style = ''
format = '[  $output ]($style inverted)'
command = 'echo -n $(($kak_cursor_line * 100 / $kak_buf_line_count))%'
when = '[ -n "$kak_cursor_line" ]'
shell = ['sh']
disabled = false

[custom.kaktime]
description = "Alternate time segment using kakoune evaluation"
format = "[%sh{date +%T} ]($style inverted)"
style = "bg:bright-green"
when = ''
shell = ['true']
disabled = true

[custom.kaklsp_err]
description = "Show errors number from kak-lsp if any"
format = "[  %opt{lsp_diagnostic_error_count}]($style inverted)"
style = "bold"
when = '[ -n "$kak_opt_lsp_diagnostic_error_count" -a "$kak_opt_lsp_diagnostic_error_count" -ne 0 ]'
shell = ['sh']
disabled = false

[custom.kaklsp_warn]
description = "Show warnings number from kak-lsp if any"
format = "[  %opt{lsp_diagnostic_warning_count} ]($style inverted)"
style = "bold"
when = '[ -n "$kak_opt_lsp_diagnostic_warning_count" -a "$kak_opt_lsp_diagnostic_warning_count" -ne 0 ]'
shell = ['sh']
disabled = false

[custom.kaklsp_hint]
description = "Show hints number from kak-lsp if any"
format = "[ %opt{lsp_diagnostic_hint_count} ﯦ ]($style inverted)"
style = "bold"
when = '[ -n "$kak_opt_lsp_diagnostic_hint_count" -a "$kak_opt_lsp_diagnostic_hint_count" -ne 0 ]'
shell = ['sh']
disabled = false

[custom.kaklsp_code_actions]
description = "Show lsp code actions"
format = "[ %opt{lsp_modeline_code_actions} ]($style inverted)"
style = "bold"
when = '[ -n "$kak_opt_lsp_modeline_code_actions" ]'
shell = ['sh']
disabled = true

[custom.kaklsp_progress]
description = "Show activity of kak-lsp if any"
format = "[ ]($style inverted)"
style = "bold"
when = '[ -n "$kak_opt_lsp_modeline_progress" ]'
shell = ['sh']
disabled = false
