[aws]
format = 'on [($profile )($region)$symbol]($style)'
style = "bold yellow"
symbol = "☁️  "
disabled = true

[battery]
full_symbol = "🔋"
charging_symbol = "⚡"
discharging_symbol = "💀"

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[](bold red)"
vicmd_symbol = "[](bold green)"

[directory]
fish_style_pwd_dir_length = 1

# docker
[docker_context]
symbol = "🐋 "
disabled = false

[gcloud]
format = 'on [$symbol$account(@$domain)(\($project\))]($style) '
style = "bold yellow"
symbol = "☁️  "
disabled = true

# git
[git_commit]
commit_hash_length = 4

[git_status]
conflicted = "🏳 "
ahead = "🏎💨"
behind = "😰"
diverged = "😵"
untracked = "🤷‍"
stashed = "📦"
modified = "📝"
staged = '[$count󰜅](bold green)'
renamed = "👅"
deleted = "🗑 "

# hostname
[hostname]
ssh_only = false
prefix = "⟪"
suffix = "⟫"
trim_at = ".companyname.com"
disabled = true

# kubernetes
[kubernetes]
symbol = "⛵ "
style = "dimmed green"
disabled = false
[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"

[custom.kakoune]
symbol = '🐈'
command = 'kcr prompt'
when = 'kcr prompt'
shell = ['sh']
description = 'The current Kakoune session and client'
style = 'green'
format = '[$symbol $output]($style)'
