[misc]
# Don't ask for confirmations
assume_yes = true

notify_each_step = true

# Disable specific steps - same options as the command line flag
disable = ["bun","containers", "gcloud", "distrobox", "protonup"]

# Ignore failures for these steps
ignore_failures = ["git_repos"]

# Run specific steps - same options as the command line flag
#only = ["system", "emacs"]

# Do not ask to retry failed steps (default: false)
#no_retry = true

# Do not set the terminal title
#set_title = false

# Cleanup temporary or old files
cleanup = true

[git]
max_concurrency = 10
# Additional git repositories to pull
repos = [
    "~/.local/share/kak/cork/plugins/*/repo",
    "~/.local/share/mdn/content",
    "~/repos/*"
]

# Arguments to pass Git when pulling Repositories
#arguments = "--rebase --autostash"

[composer]
self_update = true

# Commands to run before anything
[pre_commands]
#"Emacs Snapshot" = "rm -rf ~/.emacs.d/elpa.bak && cp -rl ~/.emacs.d/elpa ~/.emacs.d/elpa.bak"

# Custom commands
[commands]
"Bun" = "bun update -g"
"Proton" = "protonup-rs -q"

[linux]
enable_tlmgr = true
