[v1]
"aichat 0.25.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["aichat"]
"archlinux-inputs-fsck 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["archlinux-inputs-fsck"]
"attractorr 0.6.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["attractorr"]
"binsider 0.2.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["binsider"]
"cargo-binstall 1.10.16 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-binstall"]
"cargo-cache 0.8.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-cache"]
"cargo-fix 0.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-fix"]
"cargo-nextest 0.9.86 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-nextest"]
"cargo-run-bin 1.7.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-bin"]
"cargo-trend 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-trend"]
"cargo-update 16.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update",
    "cargo-install-update-config",
]
"caser-cli 0.1.0 (git+https://github.com/jtrv/caser#d5f49d542efd170047db5ab34aa7c9dd2858db8f)" = ["caser"]
"conceal 0.5.4 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cnc",
    "conceal",
]
"cpz 2.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cpz"]
"crabz 0.10.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["crabz"]
"dedoc 0.2.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["dedoc"]
"fclones 0.34.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["fclones"]
"fish-manpage-completions 0.1.0 (git+https://github.com/rust-dc/fish-manpage-completions#d927605f1d2562e7f65c1d49d8b8ea5022733869)" = ["fish-manpage-completions"]
"fls 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["fls"]
"gprepo 0.1.0 (git+https://github.com/jtrv/gprepo#da6dba30256e17c97bc0e6f6530b727200809e0b)" = ["gprepo"]
"grug 0.1.0 (git+https://github.com/jtrv/grug#bdc83b8316beb676cf5561c392e164a73cb11a74)" = ["grug"]
"handlr-regex 0.12.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["handlr"]
"hashgood 0.4.0 (git+https://github.com/thombles/hashgood#93ceef0a11e57980c967222a6504da7005895a5b)" = ["hashgood"]
"httm 0.44.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["httm"]
"huniq 2.7.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["huniq"]
"iching 0.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["iching"]
"jless 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["jless"]
"jql 8.0.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["jql"]
"just 1.38.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["just"]
"kak-lsp 18.1.0-snapshot (path+file:///home/sugimoto/.config/kak/bundle/kakoune-lsp)" = ["kak-lsp"]
"kak-popup 0.6.2-beta (registry+https://github.com/rust-lang/crates.io-index)" = ["kak-popup"]
"kak-tree-sitter 1.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["kak-tree-sitter"]
"kakpipe 0.5.7 (path+file:///home/sugimoto/.config/kak/bundle/kakpipe)" = ["kakpipe"]
"kakship 0.2.9 (path+file:///home/sugimoto/.config/kak/bundle/kakship)" = ["kakship"]
"kanata 1.6.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["kanata"]
"ktsctl 1.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["ktsctl"]
"lemmeknow 0.8.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["lemmeknow"]
"macchina 6.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["macchina"]
"magic-wormhole-cli 0.7.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["wormhole-rs"]
"markdown-oxide 0.24.0 (git+https://github.com/feel-ix-343/markdown-oxide#23f4d84fc64cc7626ecad44b7bf6fad2561cdcd3)" = ["markdown-oxide"]
"pay-respects 0.6.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["pay-respects"]
"protonup-rs 0.8.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["protonup-rs"]
"rargs 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rargs"]
"ripdrag 0.4.10 (registry+https://github.com/rust-lang/crates.io-index)" = ["ripdrag"]
"rmz 2.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rmz"]
"rustscan 2.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rustscan"]
"rusty-man 0.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rusty-man"]
"rustywind 0.23.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["rustywind"]
"scaphandre 1.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["scaphandre"]
"sccache 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["sccache"]
"secli 1.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["secli"]
"sendme 0.20.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["sendme"]
"skanuvaty 0.2.1 (git+https://github.com/Esc4iCEscEsc/skanuvaty#33a007edf5502bff6dd0583f8cf6f366d9ead11a)" = ["skanuvaty"]
"skyspell 3.0.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["skyspell"]
"skyspell_kak 2.0.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["skyspell-kak"]
"sniffglue 0.16.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["sniffglue"]
"speedtest-rs 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["speedtest-rs"]
"t-rec 0.7.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["t-rec"]
"thesauromatic 0.0.11 (registry+https://github.com/rust-lang/crates.io-index)" = ["thesauromatic"]
"topgrade 16.0.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["topgrade"]
"two_percent 0.12.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["sk"]
"vopono 0.10.10 (registry+https://github.com/rust-lang/crates.io-index)" = ["vopono"]
"wthrr 1.2.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["wthrr"]
"zet 2.0.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["zet"]
