[clipcatctl]
toolchain = "stable"
default_features = true
features = []
[clipcat-menu]
toolchain = "stable"
default_features = true
features = []
[clipcatd]
toolchain = "stable"
default_features = true
features = []
[kanata]
toolchain = "nightly"
default_features = true
features = ['cmd']
