[build]
rustc-wrapper = "/usr/bin/sccache"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold", "-C", "opt-level=3", "-C", "target-cpu=native"]

[registries.crates-io]
protocol = "sparse"
