matches:

# ENGLISH PROGRAMMING LANGUAGE

  - trigger: ",,idk"
    replace: "I don't know"

  - trigger: ",,ins"
    replace: "I'm not sure, but I can find out"

  - trigger: ",,ijrn"
    replace: "I'll join right now,"

  - trigger: ",,lmc"
    replace: "Let me check..."

  - trigger: ",,np"
    replace: "No problem"

  - trigger: ",,tia"
    replace: "Thanks, I appreciate it"

  - trigger: ",,ty"
    replace: "Thank you"

  - trigger: ",,yw"
    replace: "You're welcome"

  - trigger: ",,mta"
    replace: "This should be good to go now, moving this along."

# HTML

  - trigger: ",,hdoc"
    replace: |
      <!DOCTYPE html>

  - trigger: ",,hmc"
    replace: |
      <meta charset="UTF-8">

  - trigger: ",,hmv"
    replace: |
      <meta name="viewport" content="width=device-width, initial-scale=1">

  - trigger: ",,hma"
    replace: |
      <meta name="author" content="$|$">

  - trigger: ",,hmd"
    replace: |
      <meta name="description" content="$|$">

  - trigger: ",,hmk"
    replace: |
      <meta name="keywords" content="$|$">

  - trigger: ",,hmt"
    replace: |
      <title>$|$</title>

  - trigger: ",,hd"
    replace: |
      <div>$|$</div>

  - trigger: ",,hhe"
    replace: |
      <head>$|$</head>

  - trigger: ",,hbo"
    replace: |
      <body>$|$</body>

  - trigger: ",,hat"
    replace: |
      <a href="">$|$</a>

  - trigger: ",,hbt"
    replace: |
      <button type="button">$|$</button>

  - trigger: ",,hsti"
    replace: |
      <style>$|$</style>

  - trigger: ",,hste"
    replace: |
      <link rel="stylesheet" type="text/css" href="$|$">

  - trigger: ",,hsci"
    replace: |
      <script>$|$</script>

  - trigger: ",,hsce"
    replace: |
      <script type="text/javascript" src="$|$"></script>

  - trigger: ",,hfo"
    replace: |
      <form action="" method="">$|$</form>

  - trigger: ",,hla"
    replace: |
      <label for="">$|$</label>

  - trigger: ",,hsu"
    replace: |
      <input type="submit" value="$|$">

  - trigger: ",,hint"
    replace: |
      <input type="text" name="" id="">

  - trigger: ",,hinp"
    replace: |
      <input type="password" name="" id="">

  - trigger: ",,hinr"
    replace: |
      <input type="radio" name="" id="" value="">

  - trigger: ",,hinc"
    replace: |
      <input type="checkbox" name="" id="" value="">

  - trigger: ",,hinf"
    replace: |
      <input type="file" name="" id="">

# JAVASCRIPT

  - trigger: ",,jfn"
    replace: |
      function $|$() { }

  - trigger: ",,jaf"
    replace: |
      const $|$ = () =>

  - trigger: ",,jwl"
    replace: |
      while ($|$){ }

  - trigger: ",,jf+"
    replace: |
      for (let i = 0; i < $|$.length; i++){ }

  - trigger: ",,jf-"
    replace: |
      for (let i = 0; i >= 0; i--){ }

  - trigger: ",,jfi"
    replace: |
      for (let $|$ in ){ }

  - trigger: ",,jfo"
    replace: |
      for (let $|$ of ){ }

  - trigger: ",,jcl"
    replace: |
      console.log($|$)

  - trigger: ",,jce"
    replace: |
      console.error($|$)

  - trigger: ",,jctm"
    replace: |
      console.time("$|$")

  - trigger: ",,jcte"
    replace: |
      console.timeEnd("$|$")

  - trigger: ",,jdo"
    replace: |
      const {$|$} = ;

  - trigger: ",,jda"
    replace: |
      const [$|$] = ;

  - trigger: ",,jgi"
    replace: |
      document.getElementById("$|$")

  - trigger: ",,jgc"
    replace: |
      document.getElementByClassName("$|$")

  - trigger: ",,jqs"
    replace: |
      document.querySelector("$|$")

  - trigger: ",,jqa"
    replace: |
      document.querySelectorAll("$|$")

  - trigger: ",,jcf"
    replace: |
      document.createDocumentFragment("$|$")

  - trigger: ",,jsi"
    replace: |
      setInterval(() => {$|$}, interval)

  - trigger: ",,jso"
    replace: |
      setTimeout(() => {$|$}, delay)

  - trigger: ",,jst"
    replace: |
      JSON.stringify("$|$")

  - trigger: ",,jpe"
    replace: |
      process.exit("$|$")

  # JAVASCRIPT ALGO TEMPLATES

  - trigger: ",,jabs"
    replace: |
      function binarySearch(arr, target) {
          let left = 0;
          let right = arr.length - 1;
          let first_true_index = -1;

          function feasible(val){
            return (val $|$ target)
          }

          while (left <= right) {
              let mid = Math.floor((left + right) / 2);
              if (feasible(arr[mid])) {
                  first_true_index = mid;
                  right = mid - 1;
              } else {
                  left = mid + 1;
              }
          }
          return first_true_index;
      }


# DYNAMIC / SHELL

  # Print the current date
  - trigger: ",,date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Print the output of a shell command
  - trigger: ",,shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"
