finder = "dmenu"

[log]
# Emit log message to systemd-journald.
emit_journald = true
# Log level.
level = "INFO"

# Options for "dmenu".
[dmenu]
# Length of line.
line_length = 100
# Length of menu.
menu_length = 30
# Prompt of menu.
menu_prompt = ""
# Extra arguments to pass to `dmenu`.
extra_arguments = [
  "-fn",
  "'pixelsize=18:antialias=true'",
  "-nb",
  "rgb:18/18/25",
  "-nf",
  "rgb:cd/d6/f4",
  "-sb",
  "rgb:ca/a0/f6",
  "-sf",
  "rgb:18/18/25"
]
